name: Build MyDistro ISO

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "scripts/**"
      - ".github/workflows/build-iso.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установить зависимости сборки
        run: |
          apk update
          apk add --no-cache \
            abuild alpine-conf syslinux xorriso squashfs-tools \
            grub grub-efi mtools dosfstools \
            bash coreutils fakeroot sudo

      - name: Права на выполнение для скриптов профиля
        run: |
          chmod +x scripts/mkimg.mydistro.sh scripts/genapkovl-mydistro.sh scripts/mkimage.sh

      - name: Ключи для подписи apkindex/modloop
        run: abuild-keygen -a -i -n

      - name: Больше места под TMPDIR
        run: |
          mkdir -p /work/tmp
          echo "TMPDIR=/work/tmp" >> "$GITHUB_ENV"

      - name: Собрать ISO
        working-directory: scripts
        run: |
          ./mkimage.sh \
            --profile mydistro \
            --outdir /work/out \
            --arch x86_64 \
            --repository http://dl-cdn.alpinelinux.org/alpine/v3.22/main \
            --repository http://dl-cdn.alpinelinux.org/alpine/v3.22/community

      - name: Загрузить артефакт
        uses: actions/upload-artifact@v4
        with:
          name: mydistro-iso
          path: /work/out/*.iso
